blog = controllers.blog
blog.enabled = True
site.url = "http://i3wm.org/"
blog.path = "/blog"
blog.name = "i3 - improved tiling wm - blog"
blog.description = "News about the i3 window manager"
blog.timezone = "Europe/Berlin"
blog.posts_per_page = 5
blog.disqus.enabled = False
